chat/urls.py
# chat/urls.py
from django.urls import path

from . import views
from . import tasks
app_name = "chat"
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    path('<str:room_name>/add', tasks.message_add, name='message_add'),
    path('<str:room_name>/remove', tasks.room_remove, name='room_remove'),
]

mysite/urls.py
# mysite/urls.py

from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.conf import settings
from .views import *
from .api import api
from custommiddle.urls import api as test_api
import debug_toolbar
urlpatterns = [
    path('',index,name='index'),
    path('test',test,name='test'),
    path('token/',test_api.urls),
    path('accounts/',include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('trades/', include('trades.urls')),
    path('admin/', admin.site.urls),
    path('api/', api.urls),
]
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),

#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),

#     ] + urlpatterns

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model  
# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=20,unique=True)
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    
    
    def __str__(self):
        return self.name
class Messages(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,null=True,blank=True)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    message = models.TextField()
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    
    

chat/views.py
# chat/views.py
from asgiref.sync import sync_to_async
from django.http import JsonResponse
from django.shortcuts import render,redirect
from .models import *
from .tasks import *

@sync_to_async
def index(request):
    rooms = Room.objects.all()
    test = request.META
    context={'rooms':rooms,'test':test}
    return render(request, 'chat/index.html',context)
        
def room(request, room_name):
    room_name = ''.join(char for char in room_name if char.isalnum())
    rooms = Room.objects.all()
    room = Room.objects.filter(name=room_name).first()
    if not room:
        if room_name != "":
            room = Room(name=room_name)
            room.save()
        return redirect('chat:index')
    else:
        messages = room.messages_set.filter(room=room)
        logs = ''
        if messages:
            for message in messages:
                if message.user:
                    cur_user = message.user.username
                else:
                    cur_user = "낯선상대"
                logs = f"{cur_user} : {message.message}\n" + logs
        clean_message.delay(room.id).get()
        #get_flexible_models.delay('room')
        context={'rooms':rooms,'room': room,'messages':logs}
        return render(request, 'chat/room.html', context)

chat/templates/chat/index.html
{% extends 'layout.html' %}
{% block title %}
<title>채팅방 로비</title>
{% endblock %}
{% block layout %}
    <div>
        {% if result %}
        {{result}}
        {% endif%}
        {% if test %}
        {{test}}
        {% endif%}
    </div>
    <div>
        What chat room would you like to enter?<br>
        <input id="room-name-input" type="text" size="100"><br>
        <input id="room-name-submit" type="button" value="Enter">
    </div>
    <button id="test" value="test">test</button>
    {% for room in rooms %}
    <div> {{forloop.counter}} : {{room}}
        <a href="{% url 'chat:room' room.name %}">입장</a>
        <a href="{% url 'chat:room_remove' room.name %}">제거</a>
    </div>
    {% endfor %}
{% endblock %}
{% block footer %}
    <script>
        document.querySelector('#test').onclick = function(){
                notifySocket.send(
                    JSON.stringify(
                        {
                            'message':'test',
                            'username':'test'
                        }
                    )
                );
                console.log("testsucceed")
            }
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';           
            document.querySelector('#room-name-input').focus();
        };
        
        const notifySocket = new WebSocket(
            'wss://'
            + window.location.host
            + '/ws/notify/'
        );
        notifySocket.onopen = function (e){
            console.log(e.timeStamp)
            notifySocket.send(
                JSON.stringify(
                    {
                        'message':'test',
                        'username':'test'
                    }
                )
            );
            console.log("testsucceed")
        }
    </script>
    
{% endblock %}

chat/templates/chat/room.html
{% extends 'layout.html' %}
{% block title %}
<title>채팅방 {{room.name}}</title>
{% endblock %}
{% block layout %}
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room.name|json_script:"room-name" }}
    {{ user.username|json_script:"user-name"}}
    {{ messages|json_script:"logs"}}
{% endblock %}
{% block footer %}
    <script>
        const logs = JSON.parse(document.getElementById('logs').textContent);
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        const userName = JSON.parse(document.getElementById('user-name').textContent);

        document.querySelector('#chat-log').value += logs;

        const url = 'wss://' + window.location.host+ '/ws/chat/'+ roomName + '/?asd=23'
        
        console.log(url)
        const chatSocket = new WebSocket(url);
        chatSocket.onopen = function (e){
            console.log(e.timeStamp);
            chatSocket.send(
                JSON.stringify(
                    {
                        'message':"님이 입장하였습니다",
                        'username' : userName,
                    }
                )
            );
        }
        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            let author = data.author || "낯선상대"
            console.log(data)
            document.querySelector('#chat-log').value = (
                author +
                " : " +
                data.message + '\n') + document.querySelector('#chat-log').value;
        };
        const notifySocket = new WebSocket(
            'wss://'
            + window.location.host
            + '/ws/notify/'
        );
        notifySocket.onmessage = function(e){
            console.log(e.data)
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;   
            if (message){
                chatSocket.send(JSON.stringify({
                    'message': message,
                    'username': userName,
                }));
                $.get(
                    "{% url 'chat:message_add' room.name %}",
                    {
                        'username':userName,
                        'message':message,                    
                    },
                    function(data){
                        console.log(data);
                    }
                    ,'json'
                )
            }
            messageInputDom.value = '';
        };
    </script>
{% endblock %}